builds:
  - binary: ngxcpd
    ldflags:
      - -s -w -X github.com/maetthu/ngxcpd/internal/lib/version.Version={{.Version}} -X github.com/maetthu/ngxcpd/internal/lib/version.Commit={{.Commit}} -X github.com/maetthu/ngxcpd/internal/lib/version.Date={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archive:
  format: tar.gz
  files:
    - LICENSE
    - README.md
