version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/root:/usr/share/nginx/html:ro
      - /var/cache/nginx
    ports:
      - "80:80"
      - "8080:8080"