version: '3'
services:
  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf:ro
      - ./testdata/cache_files:/srv/cache
    ports:
      - "8080:8080"
    user: ${UID}
  generator:
    build: ./docker/generator
